import type { AEExpression, ExpressionParameter } from "./ae-expression-types";

const number = (
	name: string,
	defaultValue: number,
	min: number,
	max: number,
	step: number,
	description: string,
	unit?: string,
): ExpressionParameter => ({
	name,
	type: "number",
	defaultValue,
	min,
	max,
	step,
	description,
	unit,
});
const string = (
	name: string,
	defaultValue: string,
	description: string,
): ExpressionParameter => ({ name, type: "string", defaultValue, description });

export const AE_EXPRESSIONS: AEExpression[] = [
	{
		id: "wiggle",
		category: "animation",
		name: "Wiggle",
		description: "ランダムな動きを生成します.自然な揺れやノイズ効果に最適.",
		template: "wiggle({frequency}, {amplitude})",
		parameters: [
			number("frequency", 2, 0.1, 20, 0.1, "振動の頻度（回/秒）", "Hz"),
			number("amplitude", 50, 0, 500, 1, "振動の幅", "px"),
		],
		example: "wiggle(2, 50)",
		difficulty: "beginner",
		usageCount: 0,
		documentation:
			"wiggle()関数は、指定された頻度と振幅でランダムな動きを生成します.第1引数は1秒間の振動回数、第2引数は振動の幅を指定します.自然な手ブレやノイズ効果を作成する際に最も使用される基本的なエクスプレッションです.",
		tags: ["animation", "random", "movement", "noise"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["random", "noise"],
	},
	{
		id: "loopOut",
		category: "animation",
		name: "Loop Out",
		description: "アニメーションをループさせます.キーフレーム後の動作を制御.",
		template: 'loopOut("{type}", {numKeyframes})',
		parameters: [
			{
				name: "type",
				type: "select",
				defaultValue: "cycle",
				options: ["cycle", "pingpong", "offset", "continue"],
				description: "ループの種類",
			},
			number("numKeyframes", 0, 0, 10, 1, "ループするキーフレーム数（0=全て）"),
		],
		example: 'loopOut("cycle")',
		difficulty: "beginner",
		usageCount: 0,
		documentation:
			"loopOut()関数は、キーフレームアニメーションの最後のキーフレーム以降の動作を制御します.cycle（繰り返し）、pingpong（往復）、offset（オフセット付き繰り返し）、continue（最後の値を継続）の4つのモードがあります.",
		tags: ["animation", "loop", "keyframe", "cycle"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["loopIn", "loopInDuration"],
	},
	{
		id: "time-rotation",
		category: "animation",
		name: "Time-based Rotation",
		description: "時間に基づいた回転アニメーション.一定速度での回転に使用.",
		template: "time * {speed}",
		parameters: [
			number("speed", 360, -1800, 1800, 10, "回転速度（度/秒）", "deg/s"),
		],
		example: "time * 360",
		difficulty: "beginner",
	},
	{
		id: "bounce",
		category: "animation",
		name: "Bounce",
		description: "バウンス効果を作成.弾むような動きを表現.",
		template:
			"amp = {amplitude}; freq = {frequency}; decay = {decay}; n = 0; if (numKeys > 0) { n = nearestKey(time).index; if (key(n).time > time) { n--; } } if (n == 0) { t = 0; } else { t = time - key(n).time; } if (n > 0 && t < 1) { v = velocityAtTime(key(n).time - thisComp.frameDuration/10); value + v*amp*Math.sin(freq*t*2*Math.PI)/Math.exp(decay*t); } else { value; }",
		parameters: [
			number("amplitude", 0.8, 0, 2, 0.1, "バウンスの強さ"),
			number("frequency", 4, 1, 10, 0.5, "バウンスの頻度", "Hz"),
			number("decay", 8, 1, 20, 1, "減衰率"),
		],
		example: "bounce(0.8, 4, 8)",
		difficulty: "advanced",
	},
	{
		id: "sine-wave",
		category: "effect",
		name: "Sine Wave",
		description: "サイン波を使った周期的な動き.波のような滑らかな動作.",
		template: "Math.sin(time * {frequency}) * {amplitude} + {offset}",
		parameters: [
			number("frequency", 2, 0.1, 10, 0.1, "波の頻度", "Hz"),
			number("amplitude", 100, 0, 500, 10, "波の振幅", "px"),
			number("offset", 0, -500, 500, 10, "オフセット値", "px"),
		],
		example: "Math.sin(time * 2) * 100",
		difficulty: "intermediate",
	},
	{
		id: "random-values",
		category: "effect",
		name: "Random Values",
		description: "ランダムな値を生成.シード値で再現可能なランダム性.",
		template: "seedRandom({seed}, true); random({min}, {max})",
		parameters: [
			number("seed", 1, 1, 1000, 1, "シード値（再現性のため）"),
			number("min", 0, -1000, 1000, 1, "最小値"),
			number("max", 100, -1000, 1000, 1, "最大値"),
		],
		example: "seedRandom(1, true); random(0, 100)",
		difficulty: "intermediate",
	},
	{
		id: "scale-pulse",
		category: "transform",
		name: "Scale Pulse",
		description: "脈動するスケールアニメーション.ハートビートのような効果.",
		template:
			"[{baseScale} + Math.sin(time * {frequency}) * {amplitude}, {baseScale} + Math.sin(time * {frequency}) * {amplitude}]",
		parameters: [
			number("baseScale", 100, 10, 200, 5, "基本スケール", "%"),
			number("frequency", 4, 0.5, 20, 0.5, "脈動の頻度", "Hz"),
			number("amplitude", 20, 0, 100, 5, "脈動の強さ", "%"),
		],
		example: "[100 + Math.sin(time * 4) * 20, 100 + Math.sin(time * 4) * 20]",
		difficulty: "intermediate",
	},
	{
		id: "opacity-flicker",
		category: "transform",
		name: "Opacity Flicker",
		description: "点滅効果.ランダムまたは規則的な明滅を作成.",
		template: "{baseOpacity} + Math.sin(time * {frequency}) * {amplitude}",
		parameters: [
			number("baseOpacity", 80, 0, 100, 5, "基本透明度", "%"),
			number("frequency", 8, 1, 30, 1, "点滅の頻度", "Hz"),
			number("amplitude", 20, 0, 50, 5, "点滅の強さ", "%"),
		],
		example: "80 + Math.sin(time * 8) * 20",
		difficulty: "beginner",
	},
	{
		id: "clamp-values",
		category: "utility",
		name: "Clamp Values",
		description: "値を指定範囲内に制限.最小値と最大値の間に値を収める.",
		template: "clamp({value}, {min}, {max})",
		parameters: [
			string("value", "value", "制限する値（プロパティ名）"),
			number("min", 0, -1000, 1000, 1, "最小値"),
			number("max", 100, -1000, 1000, 1, "最大値"),
		],
		example: "clamp(value, 0, 100)",
		difficulty: "beginner",
		usageCount: 0,
		documentation:
			"clamp()関数は値を指定された範囲内に制限します.値が最小値より小さい場合は最小値を、最大値より大きい場合は最大値を返します.アニメーションの値を安全な範囲内に保つために使用されます.",
		tags: ["utility", "math", "limit", "range"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["linear", "ease"],
	},
	{
		id: "linear-interpolation",
		category: "utility",
		name: "Linear Interpolation",
		description: "線形補間.時間に基づいて値を滑らかに変化させる.",
		template: "linear(time, {startTime}, {endTime}, {startValue}, {endValue})",
		parameters: [
			number("startTime", 0, 0, 10, 0.1, "開始時間", "s"),
			number("endTime", 2, 0, 10, 0.1, "終了時間", "s"),
			number("startValue", 0, -1000, 1000, 1, "開始値"),
			number("endValue", 100, -1000, 1000, 1, "終了値"),
		],
		example: "linear(time, 0, 2, 0, 100)",
		difficulty: "intermediate",
		usageCount: 0,
		documentation:
			"linear()関数は線形補間を行います.指定された時間範囲内で値を滑らかに変化させることができます.アニメーションの開始値と終了値を時間に基づいて補間します.",
		tags: ["utility", "interpolation", "time", "animation"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["ease", "easeIn", "easeOut"],
	},
	{
		id: "ease-in-out",
		category: "animation",
		name: "Ease In Out",
		description: "イーズイン・アウトアニメーション.滑らかな加速・減速効果.",
		template: "ease({t}, {tMin}, {tMax}, {value1}, {value2})",
		parameters: [
			string("t", "time", "時間変数"),
			number("tMin", 0, 0, 10, 0.1, "開始時間", "s"),
			number("tMax", 1, 0, 10, 0.1, "終了時間", "s"),
			number("value1", 0, -1000, 1000, 1, "開始値"),
			number("value2", 100, -1000, 1000, 1, "終了値"),
		],
		example: "ease(time, 0, 1, 0, 100)",
		difficulty: "intermediate",
		usageCount: 0,
		documentation:
			"ease()関数は滑らかなイージング効果を提供します.開始時はゆっくり加速し、終了時はゆっくり減速する自然なアニメーションカーブを作成します.",
		tags: ["animation", "easing", "smooth", "curve"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["easeIn", "easeOut", "linear"],
	},
	{
		id: "posterize-time",
		category: "effect",
		name: "Posterize Time",
		description:
			"時間をポスタライズ.フレームレートを下げてストップモーション効果.",
		template: "posterizeTime({framesPerSecond}); {expression}",
		parameters: [
			number("framesPerSecond", 12, 1, 60, 1, "フレームレート", "fps"),
			string("expression", "value", "適用するエクスプレッション"),
		],
		example: "posterizeTime(12); wiggle(2, 50)",
		difficulty: "intermediate",
		usageCount: 0,
		documentation:
			"posterizeTime()関数は時間の解像度を下げ、指定されたフレームレートでエクスプレッションを評価します.ストップモーションのような効果や、意図的にカクカクした動きを作成する際に使用します.",
		tags: ["effect", "time", "framerate", "stopmotion"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["time", "wiggle"],
	},
	{
		id: "value-at-time",
		category: "utility",
		name: "Value At Time",
		description: "指定時間での値を取得.過去や未来の値を参照.",
		template: "valueAtTime(time - {offset})",
		parameters: [number("offset", 1, -10, 10, 0.1, "時間オフセット", "s")],
		example: "valueAtTime(time - 1)",
		difficulty: "advanced",
		usageCount: 0,
		documentation:
			"valueAtTime()関数は指定された時間でのプロパティ値を取得します.過去の値を参照してエコー効果を作ったり、未来の値を予測したりする際に使用します.",
		tags: ["utility", "time", "reference", "echo"],
		version: "1.0",
		author: "Adobe",
		lastUpdated: "2024-01-01",
		relatedExpressions: ["time", "delay"],
	},
];

export const CATEGORY_NAMES = {
	animation: "アニメーション",
	effect: "エフェクト",
	transform: "変形",
	utility: "ユーティリティ",
};
export const DIFFICULTY_COLORS = {
	beginner: "  ",
	intermediate: "  ",
	advanced: "  ",
};
export const DIFFICULTY_NAMES = {
	beginner: "初級",
	intermediate: "中級",
	advanced: "上級",
};
