import { useCallback, useEffect, useMemo, useState } from "react";
import { AE_EXPRESSIONS } from "./ae-expression-data";
import type {
	AEExpression,
	ExportFormat,
	ParameterValue,
	SavedExpression,
} from "./ae-expression-types";
import {
	filterExpressions,
	generateExpressionCode,
	validateExpression,
} from "./ae-expression-utils";

export function useAEExpressionTool() {
	const [expressions, setExpressions] =
		useState<AEExpression[]>(AE_EXPRESSIONS);
	const [selectedExpression, setSelectedExpression] =
		useState<AEExpression | null>(null);
	const [parameterValues, setParameterValues] = useState<
		Record<string, ParameterValue>
	>({});
	const [searchTerm, setSearchTerm] = useState("");
	const [selectedCategory, setSelectedCategory] = useState("all");
	const [selectedDifficulty, setSelectedDifficulty] = useState("all");
	const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);
	const [generatedCode, setGeneratedCode] = useState("");
	const [isPreviewPlaying, setIsPreviewPlaying] = useState(false);
	const [previewTime, setPreviewTime] = useState(0);
	const [validationResult, setValidationResult] = useState(() =>
		validateExpression(""),
	);
	const [savedExpressions, setSavedExpressions] = useState<SavedExpression[]>(
		[],
	);
	const [showDocumentation, setShowDocumentation] = useState(false);
	const [showAdvancedSettings, setShowAdvancedSettings] = useState(false);
	const [copySuccess, setCopySuccess] = useState(false);
	const [exportFormat, setExportFormat] = useState<ExportFormat>("txt");

	const filteredExpressions = useMemo(
		() =>
			filterExpressions(
				expressions,
				searchTerm,
				selectedCategory,
				selectedDifficulty,
				showFavoritesOnly,
			),
		[
			expressions,
			searchTerm,
			selectedCategory,
			selectedDifficulty,
			showFavoritesOnly,
		],
	);

	useEffect(() => {
		const code = generateExpressionCode(selectedExpression, parameterValues);
		setGeneratedCode(code);
		setValidationResult(validateExpression(code));
	}, [selectedExpression, parameterValues]);

	useEffect(() => {
		const saved = localStorage.getItem("ae-expressions-saved:v1");
		if (saved) {
			try {
				setSavedExpressions(JSON.parse(saved));
			} catch (error) {
				console.error("Failed to load saved expressions:", error);
			}
		}
	}, []);

	useEffect(() => {
		if (!selectedExpression) return;
		const initialValues: Record<string, ParameterValue> = {};
		for (const param of selectedExpression.parameters)
			initialValues[param.name] = param.defaultValue;
		setParameterValues(initialValues);
	}, [selectedExpression]);

	useEffect(() => {
		let interval: NodeJS.Timeout;
		if (isPreviewPlaying)
			interval = setInterval(
				() => setPreviewTime((previous) => previous + 0.1),
				100,
			);
		return () => {
			if (interval) clearInterval(interval);
		};
	}, [isPreviewPlaying]);

	const toggleFavorite = useCallback((id: string) => {
		setExpressions((previous) =>
			previous.map((expression) =>
				expression.id === id
					? { ...expression, isFavorite: !expression.isFavorite }
					: expression,
			),
		);
	}, []);

	const saveExpression = useCallback(() => {
		if (!selectedExpression || !generatedCode) return;
		const now = new Date();
		const savedExpression: SavedExpression = {
			id: Date.now().toString(),
			name: `${selectedExpression.name} - ${now.toLocaleDateString()}`,
			code: generatedCode,
			parameters: parameterValues,
			createdAt: now.toISOString(),
			lastModified: now.toISOString(),
		};
		const updated = [...savedExpressions, savedExpression];
		setSavedExpressions(updated);
		localStorage.setItem("ae-expressions-saved:v1", JSON.stringify(updated));
	}, [selectedExpression, generatedCode, parameterValues, savedExpressions]);

	const copyToClipboard = useCallback(async () => {
		try {
			await navigator.clipboard.writeText(generatedCode);
			setCopySuccess(true);
			setTimeout(() => setCopySuccess(false), 2000);
			if (selectedExpression)
				setExpressions((previous) =>
					previous.map((expression) =>
						expression.id === selectedExpression.id
							? { ...expression, usageCount: (expression.usageCount || 0) + 1 }
							: expression,
					),
				);
		} catch (error) {
			console.error("Failed to copy to clipboard:", error);
		}
	}, [generatedCode, selectedExpression]);

	const exportExpression = useCallback(() => {
		if (!generatedCode) return;
		let content: string;
		let filename: string;
		let mimeType: string;
		if (exportFormat === "jsx") {
			content = `// After Effects Expression\n// Generated by AE Expression Tool\n// ${new Date().toISOString()}\n\n${generatedCode}`;
			filename = "expression.jsx";
			mimeType = "text/javascript";
		} else if (exportFormat === "json") {
			content = JSON.stringify(
				{
					expression: generatedCode,
					parameters: parameterValues,
					metadata: {
						name: selectedExpression?.name,
						category: selectedExpression?.category,
						difficulty: selectedExpression?.difficulty,
						generatedAt: new Date().toISOString(),
					},
				},
				null,
				2,
			);
			filename = "expression.json";
			mimeType = "application/json";
		} else {
			content = `After Effects Expression\nGenerated: ${new Date().toLocaleString()}\nExpression: ${selectedExpression?.name}\nCategory: ${selectedExpression?.category}\n\n${generatedCode}`;
			filename = "expression.txt";
			mimeType = "text/plain";
		}
		const url = URL.createObjectURL(new Blob([content], { type: mimeType }));
		const link = document.createElement("a");
		link.href = url;
		link.download = filename;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
		URL.revokeObjectURL(url);
	}, [generatedCode, exportFormat, parameterValues, selectedExpression]);

	return {
		filteredExpressions,
		selectedExpression,
		setSelectedExpression,
		parameterValues,
		searchTerm,
		setSearchTerm,
		selectedCategory,
		setSelectedCategory,
		selectedDifficulty,
		setSelectedDifficulty,
		showFavoritesOnly,
		setShowFavoritesOnly,
		generatedCode,
		isPreviewPlaying,
		setIsPreviewPlaying,
		previewTime,
		setPreviewTime,
		validationResult,
		savedExpressions,
		setSavedExpressions,
		showDocumentation,
		setShowDocumentation,
		showAdvancedSettings,
		setShowAdvancedSettings,
		copySuccess,
		exportFormat,
		setExportFormat,
		toggleFavorite,
		saveExpression,
		copyToClipboard,
		exportExpression,
		updateParameter: (name: string, value: ParameterValue) =>
			setParameterValues((previous) => ({ ...previous, [name]: value })),
	};
}
